### ISSUE TITLE
running it w/o using docker

### ISSUE THREAD

**Issue by CLG68** [carbonsilicon-ai/CarsiDock#5]
Hi,

Is it possible to run CarsiDock under a python environment w/o having to use docker?  Do you have an environment definition file that I can use?

Best,
Christian

**Comment by CLG68** [comment]
I finally figure out an environment file to create a conda env carsidock with everything.  I **really** had a hard time installing dockcpp; I had to modify a few files to make it work.  Still I end up with this:

(carsidock) christian@Linux00:/media/christian/VS1/VS/VS_CarsiDock$ python run_docking_inference.py --pdb_file example_data/4YKQ_hsp90_40_water.pdb --sdf_file example_data/4YKQ_hsp90_40.sdf --cuda_convert
read data...
@> 1795 atoms and 1 coordinate set(s) were parsed in 0.01s.
Traceback (most recent call last):
  File "run_docking_inference.py", line 74, in <module>
    main(args)
  File "run_docking_inference.py", line 31, in main
    pocket, ligand = extract_carsidock_pocket(get_abs_path(args.pdb_file),
  File "/media/christian/VS1/VS/VS_CarsiDock/src/utils/docking_utils.py", line 645, in extract_carsidock_pocket
    protein = prody.parsePDBStream(pdb_file).select('protein or water')
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/prody/atomic/atomic.py", line 232, in select
    return SELECT.select(self, selstr, **kwargs)
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/prody/atomic/select.py", line 894, in select
    indices = self.getIndices(atoms, selstr, **kwargs)
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/prody/atomic/select.py", line 952, in getIndices
    torf = self.getBoolArray(atoms, selstr, **kwargs)
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/prody/atomic/select.py", line 1003, in getBoolArray
    parser = self._getParser(selstr)
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/prody/atomic/select.py", line 1102, in _getParser
    parser.enablePackrat()
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
  File "/home/christian/anaconda3/envs/carsidock/lib/python3.8/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
TypeError: can't multiply sequence by non-int of type 'Forward'

I'm about to give up...

**Comment by gitabtion** [comment]
Hello, we do not recommend performing inference in a non-Docker environment as it may result in a decrease in performance metrics. If you really need to do so, please run the Docker image and use conda pack to package the Conda environment within the image. You can then unpack it locally for use.

**Comment by gitabtion** [comment]
Hello, we do not recommend performing inference in a non-Docker environment as it may lead to a decrease in performance metrics. If you really need to do so, there is no need to modify the code. After installing PyTorch and CUDA, you can follow the Dockerfile step-by-step to install the required dependencies. for example:


```bash
# install pytorch first...
# Install Python Requirements
pip install  dgl -f https://data.dgl.ai/wheels/cu118/repo.html  # Change cu118 to your cuda version
pip install -r /requirements.txt

# Install build-essential
sudo apt-get update && apt-get install -y build-essential

# Install pydock
mkdir ./app && cd ./app && git clone https://github.com/gitabtion/dockcpp.git
cd ./app/dockcpp && mkdir build && cd build && \
        cmake .. && make install-python-package && \
        cd ../../

# Install OpenBabel
cd ./app && git clone https://github.com/openbabel/openbabel.git
cd ./app/openbabel && mkdir build && cd build && \
    cmake .. -DPYTHON_BINDINGS=ON && make && make install && \
    cd ../../
sudo apt-get update && apt-get install -y swig
sudo pip install openbabel
```

**Comment by CLG68** [comment]
Thank you for your feedback.  I usually like to work using environments but if it is faster under a docker, it could save me a lot of time for screening a large library.  I'll try to reinstall from scratch, maybe it will solve the problems that lead to:

"TypeError: can't multiply sequence by non-int of type 'Forward'"
Thanks again,
Christian
